### ISSUE TITLE
undefined resolved account balance after calling recieve() api

### ISSUE THREAD

**Issue by OmarB97** [nanobox-cc/nano-client#1]
This is the resolved account object that we get back in the promise after calling the recieve() api:

{account: Proxy, resolvedCount: 1}
account: Proxy
[[Handler]]: Object
[[Target]]: Object
address: "hidden-for-privacy-reasons"
balance: undefined
privateKey: "hidden-for-privacy-reasons"
publicKey: "hidden-for-privacy-reasons"
representative: "nano_1kaiak5dbaaqpenb7nshqgq9tehgb5wy9y9ju9ehunexzmkzmzphk8yw8r7u"
__proto__: Object
[[IsRevoked]]: false
resolvedCount: 1
__proto__: Object

The balance seems to come back as undefined, although the block does seem to still get processed and I get the receive subscription for the processed block from my WebSocket afterward, so seems like somewhere the balance is just not getting assigned properly (?)

**Comment by mehlium** [comment]
Thanks for reporting! There was a bug when receiving that did not resolve the actual amount. This is fixed in v1.2.0. Can you try upgrading to that version?

**Comment by OmarB97** [comment]
Hey sorry for the late response, tested on 1.2.0 yesterday and I think it works now :)

**Comment by mehlium** [comment]
Thanks for testing!
