### ISSUE TITLE
Enable dPOW for send/receive transactions

### ISSUE THREAD

**Issue by OmarB97** [nanobox-cc/nano-client#16]
I think it will become increasingly important for services to respond to the networks' Dynamic Proof of Work correctly. 

Having an ability to "enable" dPOW is useful, and can signal to the nano-client to generate POW that scales with the network's current demands, rather than always do the lowest POW.

I didn't fully confirm this in the code so please LMK whether this is already the case or not :)

**Comment by mehlium** [comment]
Dynamic pow is definitely something we'd would like to get implemented in the client in the near future. Thanks for reporting this!

**Comment by mehlium** [comment]
Given the release of Nano node v22, `active_difficulty` is now voided with the new prioritization logic.
