### ISSUE TITLE
update() is not a function?

### ISSUE THREAD

**Issue by OmarB97** [nanobox-cc/nano-client#17]
I tried switching from receive() (which says now deprecated) to update() and I received an error saying it's not a function:

```
c.update is not a function
```

**Comment by mehlium** [comment]
I was a bit happy on the trigger there. Will release the new version with the implemented update-function today.

**Comment by mehlium** [comment]
Latest release includes this change: https://github.com/nanobox-cc/nano-client/releases/tag/v2.0.1
